### ISSUE TITLE
Doesn't work with multiple Entry Points

### ISSUE THREAD

**Issue by rlindskog** [yusinto/universal-hot-reload#1]
I added a named entry point to the webpack.config.client and it wouldn't work.  Any ideas?

webpack.config.client.js
```
module.exports = {
  entry: {
    client: [
      'webpack-dev-server/client?' + webpackDevServerUrl,
      'webpack/hot/only-dev-server',
      './src/client/index'
    ]
  },
  ...
}
```
Error Message:

> universal-hot-reload/lib/getDevServerPort.js:22
>   var devServerEntry = clientConfig.entry.find(function (entry) {
>                                           ^
> TypeError: clientConfig.entry.find is not a function

**Comment by yusinto** [comment]
This is not supported yet. At the moment, you'll need to have two separate
configs, one for client and one for server. It's a good idea though, if you
would submit a pull request, it would be most welcome.

**Comment by yusinto** [comment]
I'll close this now due to the lack of response for a pull request. The workaround is to have 2 separate configs for client and server.
