### ISSUE TITLE
universalHotReload is not a function

### ISSUE THREAD

**Issue by arnold-iakab** [yusinto/universal-hot-reload#2]
Hi! I wanted to point out that the import of the universal-hot-reload module in `server/index.js` has to be made like this:
`require('universal-hot-reload').default;`

Had a bit of a headache figuring this out. Update the documentation and keep up the good work!

**Comment by yusinto** [comment]
Apologies for that. The example project was correct but the readme instruction was wrong. I have corrected this now, thanks for the heads up!
