### ISSUE TITLE
Didn't work on windows (PR ready)

### ISSUE THREAD

**Issue by Alex-Ferreli** [yusinto/universal-hot-reload#4]
Hi Yusinto, ty for the awesome package!

I have found a problem in your package in windows enviroment. The problem is [here](https://github.com/yusinto/universal-hot-reload/blob/master/src/index.js#L14).

You are concatenating the output path with the file name with "/" the is the right separator in Linux and MAC but didn't work in windows. Thae first compilation work fine but when i change a file the server stop and didn't start anymore. The problem is that the require cache save it with the right slash (Node.js fix this slash inconsistency before save the result in the cache). When you tro to clean the cache in the "clearRequireCache.js" file you are clearing the wrong path (before the Node.js fix).

The core Node.js module "path" contains the "sep" variable that work right in all OS. Or you can use "resolve" function to fix the problem (always in the "path" module).

I can do the PR if you want.

Thank you for your work!

**Comment by yusinto** [comment]
Hi Alex thanks for reporting the issue. Sounds like you already have a
couple of good solutions there. If you can help submit a pr that will be
much appreciated. Thank you.

**Comment by Alex-Ferreli** [comment]
The PR should be ok. It's the first time that i make a PR so something could be wrong.
