### ISSUE TITLE
Old dependencies and deprecated modules

### ISSUE THREAD

**Issue by taseenb** [yusinto/universal-hot-reload#6]
Thanks for sharing this great app. I've been looking for a decent setup to develop Front end with SSR and this is the best I've found.

I would like to use this for a new project but there are a number of issues related to old dependencies:

- It doesn't work with Node 10.13.0 (current LTS).
- Babel still uses old beta modules.
- `webpack-serve` was deprecated and `webpack-dev-sever` should be used instead.

These are the latest versions of all modules (and they work with Node 10 but there's a problem with `webpack-serve` related to a breaking change in the last version):

```
"dependencies": {
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10",
    "webpack-node-externals": "^1.7.2",
    "webpack-serve": "^2.0.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.6",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "^7.0.0-0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.4",
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-friendly-formatter": "^4.0.0",
    "eslint-plugin-babel": "^5.2.1",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "jest": "^23.6.0",
    "rimraf": "^2.6.2",
    "testdouble": "^3.6.0"
  }
```

FYI the easiest way to upgrade all the modules is to set all versions to `"0.0.0"` and then run `npx npm-check-updates` and then `npm install` again. Do you think you will update this?

**Comment by yusinto** [comment]
@taseenb I have fixed all the issues you mentioned in [v2](https://github.com/yusinto/universal-hot-reload/releases/tag/v2.0.0)

Please check it out and let me know if it works.

**Comment by taseenb** [comment]
Thanks for the very quick update. I am trying to adapt your tool to my application but I keep getting a **EADDRINUSE** error. I find 2 processes related to tcp at port 8088 (the port I'm trying to use):

```
COMMAND    PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    5531 taseenb  148u  IPv4 0xadd490f54b37f68b      0t0  TCP localhost:50163->localhost:radan-http (ESTABLISHED)
node      5850 taseenb   30u  IPv4 0xadd490f54c26200b      0t0  TCP localhost:radan-http (LISTEN)
```

My Webpack client config:

```
const webpackServeUrl = 'http://localhost:8088'

// and in output:
output: {
  path: path.join(__dirname, '../public/assets'),
  filename: 'js/bundle.js',
  publicPath: `${webpackServeUrl}/public/`,
}
```

In `package.json`:

`babel-node ./src/server/hot-reload.js`

In `hot-reload.js`:

```
import config from './config'
import { getDevServerBundleUrl } from 'universal-hot-reload'
import webpackClientConfig from '../../webpack/webpack-dev.config'

if (config.env === 'development') {
  const UniversalHotReload = require('universal-hot-reload').default

  UniversalHotReload(
    require('../../webpack/webpack-node.config')('development'),
    require('../../webpack/webpack-dev.config')
  )
}

// Important: gets webpack-dev-server url from your client config
export const devServerBundleUrl = getDevServerBundleUrl(webpackClientConfig)
```

My http server:

```
import app from './express-app'
import http from 'http'

const port = 8080
app.set('port', port)
const server = http.createServer(app)

// Important: the listen method returns a http.server object which must be default exported
// so universal-hot-reload can access it
export default server.listen(port, () => {
  console.log(`Listening at ${port}`)
})
```

Any idea on why the EADDRINUSE?

**Comment by taseenb** [comment]
Thanks a lot for fixing the problem so quickly. My setup is working quite well now with the latest Babel and Node. Yet the browser does not reload when I change files on the server (even if the server bundle is created and i get the message `Server bundled & restarted`). Is that not a feature?

If I may suggest something, I think that the example (which dependencies are not up to date) and the REAME are a bit confusing and it took me a while to figure out how to apply the tool to my real application. The difference between `index.js` and `server.js` is not clear, unless you know how your script works behind the scenes.
In the real world you only use this in development, so I would suggest to rename `index.js` to `hot-reload.js` (or `dev-server.js`) in the example. In production you will run `server.js`, with a condition to select the right bundle url. For users, it'd be very helpful to explicitly show how to deal with both development and production environments in the example. Even a minimal example would help imo.
